version: "3"

services:
  chirpstack-gateway-bridge:
    container_name: chirpstack-gateway-bridge
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
      - BROKERCHIRP=ChirpStackApp
    depends_on:
      - mosquitto
  
  chirpstack-gateway-bridge-basicstation:
    container_name: chirpstack-gateway-bridge-basicstatio
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    ports:
      - 3001:3001
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/mosquitto/config/:/mosquitto/config/
  
  p4sniffer:
    image: dnredson/p4sniffer
    container_name: p4sniffer
    network_mode: "host"
    privileged: true
    working_dir: /switch
    tty: true
    stdin_open: true      

volumes:
  postgresqldata:
  redisdata:
