version: "3"

services:
  ChirpStackApp:
    container_name: ChirpStackApp
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mqttIotAgent
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
      - IOTGATEWAY=${EnvIG}
    ports:
      - 8080:8080
      - 9999:9999
    networks:
      - deploy
      
  chirpstack-rest-api:
    container_name:: chirpstack-rest-api
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack
    networks:
      - deploy

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - deploy

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data
    networks:
      - deploy

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/mosquitto/config/:/mosquitto/config/
    networks:
      - deploy

volumes:
  postgresqldata:
  redisdata:
  
networks:
  deploy:
    name: deploy
  
